- data/packages.php
I am not sure what you mean "modified files" and what you want by different URL, I assuming this does not apply to me as they are all served from my server.
I did bump the versions (& incl. resources versions) of the affected packages as well.
> Update jackz's scripts' urls & corrected dependencies / resources

- data/packages.php
If it gets added to the repository i will delete the auto updater inside the script as fast as i can.
> Update packages.php added NovaHook

- data/packages.php
Add SlotBot to lua scripts repo
> Add SlotBot

- data/packages.php
> JinxScript Update 0.41.2

- data/packages.php
> Update packages.php added NovaScript

- data/packages.php
Added Novalay
Changed the author name for all my scripts to Nova
> Add NovaLay

- data/packages.php
- Add ped overlays
- Add landing gear options
- Fix bug when not setting position when leaving free edit mode
- Other small bug fixes
> Constructor 0.38

- data/packages.php
> Constructor 0.39r

- data/packages.php
> Constructor 0.39r [fixed]

- data/packages.php
Fixed issue chat and team chat opening with phone
> Update Advanced Chat

- data/packages.php
> Heist Control V 3.3.7 Update

- data/packages.php
> Add DOLOS, a trolling script

- data/packages.php
> bump dolos edition

- data/packages.php
> bump lancescript edition for bug fix

- data/packages.php
> bump betterchat edition for bug fix

- data/packages.php
> Constructor 0.42

- data/packages.php
- Updated component_resources to game version 1.68 Chop Shop
- Improved Auto-Load
> Update Custom Loadout

- data/packages.php
• Fully updated for 1.68-3095
• Improved Auto Accept
• Improved Disable Vehicle Sounds
• Improved Access Locked Vehicles
• Improved Block Orbital Cannon
• Heavily Improved Godmode Detection
• Heavily Improved Orbital Cannon Targeting Detection • Fixed Send To Activity
• Fixed Naruto Ran when jumping
• Fixed Disable Vehicle Audio causing Unusual Events • Fixed Vehicle Wheelie
• Fixed Vehicle Clumsiness
• Fixed Modified Vehicle Speed false flagging for some of the new vehicles • Fixed Anti-Cage not releasing objects you own or have no owner • Numerous other bug fixes & improvements
• Moved Orbital Cannon Options -> JinxScript > Lobby • Moved Reverse Mock Chat Messages -> JinxScript > Lobby • Added Players > JinxScript > Friendly > RP Loop
• Re-Added Players > JinxScript > Trolling > Kick …
> JinxScript Recode

- data/packages.php
> Update packages.php; bump DOLOS and BetterChat

- data/packages.php
> TriviaBot 0.9

- data/packages.php
I updated required native and some bugs were fixed that were introduced due to breaking changes in the Lua library. 
Thanks!
> Update lazscript 1.1 -> 1.3

- data/packages.php
> Update DOLOS for Pluto compatibility / merge PR from Sainan

- data/packages.php
- Add disabled message until Stand reenabled Slot rigging
> SlotBot v0.27r

- data/packages.php
> Constructor 0.49

- data/packages.php
bugfix for loading certain XML files
> Constructor 0.50.3r

- data/packages.php
> SlotBot 0.28.2r - Limit to $10mil

- data/packages.php
> fix mod color bug

- data/packages.php
Fixed Bugs
Added new detecting system for detections.
added styles in the 'Customize' list
> NovaHook Update 1.2.0

- data/packages.php
refactor file loaders into convertors
> Constructor 0.51

- data/packages.php
> Constructor 0.51.1

- data/packages.php
The original repository is no longer accessible.
> Update Jinxscript URL

- data/packages.php
> Update Heist Control
